include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_double_quotes: true
    avoid_as: true

analyzer:
  errors:
    invalid_annotation_target: ignore
    invalid_immutable_annotation: ignore
    non_constant_identifier_names: ignore
    must_be_immutable: ignore
    unnecessary_string_escapes: ignore
    
